# Generated by Django 3.1.7 on 2021-03-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210311_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '그룹', 'verbose_name_plural': '그룹'},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'verbose_name': 'LoginHistory'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
