# Generated by Django 3.1.7 on 2021-03-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210311_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, max_length=6, verbose_name='그룹코드'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.PositiveIntegerField(default=1, verbose_name='활성상태'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20, verbose_name='그룹이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group', verbose_name='그룹이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(max_length=50, verbose_name='카카오ID'),
        ),
    ]
