# Generated by Django 3.1.7 on 2021-04-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210312_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='01036955967', max_length=11),
            preserve_default=False,
        ),
    ]
