# Generated by Django 3.2 on 2021-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210506_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('name',), 'verbose_name': '그룹', 'verbose_name_plural': '그룹'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('username',), 'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
