# Generated by Django 3.2 on 2021-06-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210527_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member'),
        ),
    ]
