# Generated by Django 3.2 on 2021-06-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210603_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='affiliation',
            field=models.CharField(choices=[('직영', '직영'), ('대행점', '대행점')], default='직영', max_length=5),
            preserve_default=False,
        ),

    ]
