# Generated by Django 3.2 on 2021-05-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakao', '0002_alter_friendstalk_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendstalk',
            name='status',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
