# Generated by Django 3.2 on 2021-05-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakao', '0005_friendstalk_sended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendstalk',
            name='receiver',
            field=models.TextField(blank=True, null=True),
        ),
    ]
