# Generated by Django 3.2 on 2021-05-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakao', '0006_alter_friendstalk_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendstalk',
            options={'verbose_name': '친구톡', 'verbose_name_plural': '친구톡'},
        ),
        migrations.AddField(
            model_name='friendstalk',
            name='img_url',
            field=models.ImageField(default='https://ilhwa-pharm.s3.ap-northeast-2.amazonaws.com/ilhwa_logo.jpg', upload_to='friendstalk', verbose_name='이미지URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='btn_name',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='버튼이름'),
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='img_link',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 링크'),
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='receiver',
            field=models.TextField(blank=True, null=True, verbose_name='수신자'),
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='response_msg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='상태메세지'),
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='sended_at',
            field=models.DateTimeField(auto_now=True, verbose_name='발송일시'),
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='sender',
            field=models.CharField(max_length=15, verbose_name='발신자'),
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='status',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='발송상태'),
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='weblink_mobile',
            field=models.URLField(blank=-1, null=True, verbose_name='웹링크Mobile'),
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='weblink_pc',
            field=models.URLField(blank=True, null=True, verbose_name='웹링크PC'),
        ),
    ]
