# Generated by Django 3.2 on 2021-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakao', '0007_auto_20210518_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendstalk',
            options={'ordering': ['-sended_at'], 'verbose_name': '친구톡', 'verbose_name_plural': '친구톡'},
        ),
        migrations.AlterField(
            model_name='friendstalk',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='friendstalk', verbose_name='이미지URL'),
        ),
    ]
