# Generated by Django 3.2 on 2021-05-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakao', '0008_auto_20210527_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendstalk',
            name='sended_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='발송일시'),
        ),
    ]
