# Generated by Django 3.1.7 on 2021-03-11 18:08

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ('-updated_at',), 'verbose_name': '의약품', 'verbose_name_plural': '의약품 리스트'},
        ),
        migrations.AlterModelOptions(
            name='medicinetag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.AlterModelOptions(
            name='taggedmedicine',
            options={'verbose_name': '태그된 게시물', 'verbose_name_plural': '태그된 게시물'},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='태그는 콤마(,) 혹은 띄워쓰기로 구분해주세요', through='medicine.TaggedMedicine', to='medicine.MedicineTag', verbose_name='tag'),
        ),
    ]
