# Generated by Django 3.1.7 on 2021-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20210330_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='detail_url',
            field=models.URLField(null=True, verbose_name='디테일 정보'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='product_url',
            field=models.URLField(null=True, verbose_name='제품상세'),
        ),
    ]
