# Generated by Django 3.1.7 on 2021-03-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20210330_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.DO_NOTHING, to='medicine.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='detail_url',
            field=models.URLField(blank=True, null=True, verbose_name='디테일 정보'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='product_url',
            field=models.URLField(blank=True, null=True, verbose_name='제품상세'),
        ),
    ]
