# Generated by Django 3.2 on 2021-06-09 12:19

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20210521_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='detail_url',
            field=models.URLField(blank=True, help_text='디테일포인트 URL을 등록하면 디테일 포인트는 노출되지 않습니다', null=True, verbose_name='디테일포인트URL'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='태그(상위어,동의어)는 콤마(,) 혹은 띄워쓰기로 구분해주세요', through='medicine.TaggedMedicine', to='medicine.MedicineTag', verbose_name='태그'),
        ),
    ]
